name: Build and Test

on:
  push:
    branches:
      - ensek-task-mohamed-salah
  pull_request:
    branches:
      - ensek-task-mohamed-salah

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET 9 Preview SDK
        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/7c5d9946-26c0-4908-9391-1d2e238d9b7c/0e0a7c520e4dfc490ef1f52bafec52c6/dotnet-sdk-9.0.100-preview.3.24172.9-linux-x64.tar.gz
          mkdir -p $HOME/dotnet9
          tar zxf dotnet-sdk-9.0.100-preview.3.24172.9-linux-x64.tar.gz -C $HOME/dotnet9
          echo "$HOME/dotnet9" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/dotnet9" >> $GITHUB_ENV
          
      - name: Verify .NET SDK version
        run: dotnet --version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit and Integration Tests
        run: |
          cd Ensek.Tests
          dotnet test --no-build --verbosity normal

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.xml